apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: chrisscullpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chrisscullpipelinesjavascriptdocker 
    spec:
      containers:
        - name: chrisscullpipelinesjavascriptdocker 
          image: smccontainerregistry.azurecr.io/chrisscullpipelinesjavascriptdocker
          ports:
          - containerPort: 8080